# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectName: 'simplewebapi.csproj'
  projectPath: 'app/simplewebapi'
  archiveFileName: 'app'
  rootFolder: 'app/simplewebapi/bin'

resources:
  repositories:
  - repository: azuredevopspipelinetemplates
    type: github
    name: haripraghash/azuredevopspipelinetemplates
    endpoint: github.com_haripraghash
    ref: refs/heads/master

steps:
- task: Bash@3
  displayName: 'List contents'
  inputs:
    targetType: 'inline'
    script: ls

- template: azuredevops/pipelinetemplates/shared-template.yaml@azuredevopspipelinetemplates
  parameters:
    buildConfiguration: $(buildConfiguration)
    projectName: $(projectName)
    projectPath: $(projectPath)
    archiveFileName: $(archiveFileName)
    rootFolder: $(rootFolder)

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'app'