# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectName: 'simplewebapi.csproj'

steps:
- task: Bash@3
  displayName: 'List contents'
  inputs:
    targetType: 'inline'
    script: ll -a
- script: dotnet build $(projectName) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: 'Archive binaries'
  inputs:
    rootFolderOrFile: \aspnetcore-webapi\app\simplewebapi\bin\Debug\netcoreapp3.1
    archiveType: 'zip'
    includeRootFolder: false
    archiveFile: $(Build.ArtifactStagingDirectory)\app.zip
    replaceExistingArchive: true

# - task: CopyFiles@2
#   displayName: 'Copy infrastructure files to staging directory'
#   inputs:
#     Contents: '**\Infrastructure\*'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)/Infrastructure'
#     flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'app'